/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "Tx_1_aliases.h"
#include "Tx_1.h"
#include "isr_tx.h"
#include "isr_rx.h"
#include "Opamp_1.h"
#include "Vout_1_aliases.h"
#include "Vout_1.h"
#include "INVERSOR_1_aliases.h"
#include "INVERSOR_1.h"
#include "SENSOR_1_aliases.h"
#include "SENSOR_1.h"
#include "Opamp_2.h"
#include "Vout_2_aliases.h"
#include "Vout_2.h"
#include "SENSOR_2_aliases.h"
#include "SENSOR_2.h"
#include "INVERSOR_3_aliases.h"
#include "INVERSOR_3.h"
#include "SENSOR_3_aliases.h"
#include "SENSOR_3.h"
#include "Vout_3_aliases.h"
#include "Vout_3.h"
#include "DIGITOS_aliases.h"
#include "DIGITOS.h"
#include "Opamp_3.h"
#include "INVERSOR_2_aliases.h"
#include "INVERSOR_2.h"
#include "BOTONES_aliases.h"
#include "BOTONES.h"
#include "isr_b1.h"
#include "isr_b2.h"
#include "LED_MSB_aliases.h"
#include "LED_MSB.h"
#include "BOTON_aliases.h"
#include "BOTON.h"
#include "isr_b3.h"
#include "Clock_1.h"
#include "isr_clkDigits.h"
#include "Timer_1.h"
#include "SS_A_aliases.h"
#include "SS_A.h"
#include "SS_B_aliases.h"
#include "SS_B.h"
#include "SS_C_aliases.h"
#include "SS_C.h"
#include "SS_D_aliases.h"
#include "SS_D.h"
#include "SS_E_aliases.h"
#include "SS_E.h"
#include "SS_F_aliases.h"
#include "SS_F.h"
#include "SS_G_aliases.h"
#include "SS_G.h"
#include "SS_P_aliases.h"
#include "SS_P.h"
#include "Clock_2.h"
#include "LED_LSB_aliases.h"
#include "LED_LSB.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

